import type { NextPage } from 'next';
import Head from 'next/head';
import { Button, Typography } from '@mui/material';
import Slider from '@mui/material/Slider';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{ padding: 20 }}>
          <Typography variant="h4" gutterBottom>
            Hello, Material UI!
          </Typography>
          <Button variant="contained" color="primary">
            Click Me
          </Button>
        </div>

        <div>
          <h1 className="text-3xl font-bold underline">Hello world TailwindCss!</h1>
          <p className=" text-indigo-500">samo 2</p>
        </div>

        <div>
          <Slider defaultValue={30} />
          <Slider defaultValue={30} className=" text-orange-100" />
        </div>
      </main>
    </div>
  );
};

export default Home;
